### ISSUE TITLE
[Bug]: Can't exit interactive pick mode when we want to cancel the selecting

### ISSUE THREAD

**Issue by tan-wei** [Bekaboo/dropbar.nvim#102]
### Description

When entering interactive pick mode, we can't exit the pick mode when the selecting pop menu is shown.

### nvim version

NVIM v0.10.0-dev-1303+g61f1e992ce

### dropbar.nvim version

Bekaboo/dropbar.nvim

### Operating system and version

Linux archlinux 6.1.56-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 06 Oct 2023 14:13:03 +0000 x86_64 GNU/Linux

### Minimal config

```Lua
-- Default configure file is enough

local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

Enter pick mode, and select a element, then popup menu is shown.

Now we can not exit pick mode, despite we `ESC` or something else.

### Expected behavior

We could exit pick mode at any step.

### Actual behavior

Any key will not exit pick mode, except:
  - Select a element. But it is not that conveneint if we just select the current element, because the cursor or the buffer will be reloaded
  - Use mouse and click anywhere else. But it is not that conceneit because we do not want to use mouse (it is Neovim, :-P)

**Comment by Bekaboo** [comment]
Cannot reproduce.

> Enter pick mode, and select a element, then popup menu is shown.
>
> Now we can not exit pick mode

Not sure what do you mean here. Pick mode can be exited with `<Esc>`; after selecting a element, e.g. after the drop-down menu is shown, you should immediately exit pick mode.

**Comment by tan-wei** [comment]
Sorry it is not that clear.

I think your understanding is exactly mine. I upload a gif to help me describe this:

![pick](https://github.com/Bekaboo/dropbar.nvim/assets/28227509/f4348be3-ffdc-443d-a4e8-03292920c867)

First time I try to strike several <ESC>s, nothing happens, so Ican only strike <CR> to reopen *main.cpp*.
Then second time, I try to use mouse click to exit pick mode, it sucesses.

**Comment by tan-wei** [comment]
I try it on different neovim version, it just behaves the same.

**Comment by Bekaboo** [comment]
@tan-wei Please use the mininal config for demo.

**Comment by tan-wei** [comment]
OK, I'll try.

**Comment by tan-wei** [comment]
Hmm, minimal config could reproduce this:
![demo](https://github.com/Bekaboo/dropbar.nvim/assets/28227509/8c3f1271-4e73-4d74-920f-245ef48801f7)

**Comment by Bekaboo** [comment]
Cannot reproduce. From the gif provided it seems that the pick pivots (the letters in red) disappear after a drop-down menu is opened, as expected -- so you should have already exit pick mode then. What exactly bugs you here?

> and I strike many times here

Do you mean that nvim does not respond to your key strikes?

> (you can see warnings that the current buffer is not saved) by strike .

What keys did you pressed? It is not clear from the GIF so I could not trigger the warning on my end.

P.S. Could you please upload videos instead of GIFs? It will be more convenient for me to stop and see the error messages. Thanks.

**Comment by tan-wei** [comment]
OK, I will upload a video with showing the key I input then.

> From the gif provided it seems that the pick pivots (the letters in red) disappear after a drop-down menu is opened, as expected -- so you should have already exit pick mode then. What exactly bugs you here?

There may be some misunderstandings here. Yes, before we pick a pivot, it can exit pick mode by strike <ESC>. But if I have picked up a pivot, then the drop-menu is shown, I can't close the drop-menu by strick <ESC>. Perhaps my title is incorrect: Pick mode can be exited by <ESC>, but drop-down menu is not closed by strick <ESC>.

**Comment by tan-wei** [comment]
The error messages shown on the GIF are not related to the issue. It is just because:
  - I modify the buffer
  - I reopen the buffer by select the drop-down menu with <CR>
  - neovim complains that the buffer is not saved with warning messages

**Comment by Bekaboo** [comment]
@tan-wei Drop-down menus are just floating windows, use `:q`, `:bd`, `<C-w>c` or any other ways you prefer to close a drop-down window. If you would like to use `<esc>` to close a drop-down menu, remap it to `<C-w>c` or something equivalent.
