### ISSUE TITLE
[Bug]: Calling nil (vim.lsp) /lua/dropbar/sources/lsp.lua:L343

### ISSUE THREAD

**Issue by FalcoGer** [Bekaboo/dropbar.nvim#112]
### Description

I'm using coc for lsp integration. I thought this is what disabled disabled vim's built in LSP feature. But even when I load a config where I don't load coc, it still fails. In any case, I still wish to use dropbar with treesitter.

When loading a file in nvim, I get an error.

### nvim version

NVIM v0.10.0-dev-e59cf3b3a

### dropbar.nvim version

d308748aa5ea44e9df35d2f5333cd2de148fcf3c

### Operating system and version

Ubuntu Mate 22.04 (`Linux <hostname> 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`)

### Minimal config

```Lua
set nocompatible

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

filetype off
call plug#begin(expand('~/.vim/plugged'))
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'Bekaboo/dropbar.nvim'

call plug#end()
filetype plugin indent on

if has("syntax")
  syntax on
endif

set guioptions+=a

set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set autowrite
set hidden
set mouse=a

lua << EOF
local dropbar = require('dropbar')
dropbar.setup({})
EOF
```

### Steps to reproduce

1. `nvim -u minimal.vim minimal.vim`

### Expected behavior

Loads without error.

### Actual behavior

```text
Error executing vim.schedule lua callback: ...ul/.vim/plugged/dropbar.nvim/lua/dropbar/sources/lsp.lua:343: attempt to call field 'get_clients' (a nil value)
stack traceback:
        .../.vim/plugged/dropbar.nvim/lua/dropbar/sources/lsp.lua:343: in function 'init'
        .../.vim/plugged/dropbar.nvim/lua/dropbar/sources/lsp.lua:386: in function 'get_symbols'
        .../.vim/plugged/dropbar.nvim/lua/dropbar/utils/source.lua:9: in function 'get_symbols'
        /home/<username>/.vim/plugged/dropbar.nvim/lua/dropbar/bar.lua:526: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Additional information

https://github.com/Bekaboo/dropbar.nvim/blob/d308748aa5ea44e9df35d2f5333cd2de148fcf3c/lua/dropbar/sources/lsp.lua#L343

`vim.lsp` is `nil`

**Comment by Bekaboo** [comment]
Duplicate #103, you are on a too old version of nvim nightly, please update your nvim version.
