### ISSUE TITLE
[help]: keymap to toggle dropbar

### ISSUE THREAD

**Issue by pwnwriter** [Bekaboo/dropbar.nvim#115]
Is there any way to map keys to toggle the dropbar, than just clicking over ?

```lua
  menu = {
    quick_navigation = false,
    keymaps = {
      ["<C-c>"] = "<C-w>q",
      ["h"] = "<C-w>c",
      ["l"] = function()
        local menu = require("dropbar.api").get_current_dropbar_menu()
        if not menu then
          return
        end
        local cursor = vim.api.nvim_win_get_cursor(menu.win)
        local component = menu.entries[cursor[1]]:first_clickable(cursor[2])
        if component then
          menu:click_on(component, nil, 1, "l")
        end
      end,
    },
  },
```

This is my config, i want to set `C-;` to toggle dropbar. I've gone through docx, issues but unfortunately, didn't get how'd i actually map.

**Comment by Bekaboo** [comment]
> Is there any way to map keys to toggle the dropbar

What do you mean by "toggle the dropbar"? If you mean hiding/showing the winbar, just use `:set winbar=` to hide to winbar and `:set winbar=%{%v:lua.dropbar.get_dropbar_str()%}` to show the winbar.

> ... than just clicking over?

Sorry, I don't understand here. Clicking the winbar does not toggle it. In most cases clicking on a symbol in a winbar will open a drop-down menu for that symbol.

**Comment by pwnwriter** [comment]
Oh, I apologize. What I meant to convey is that I would like to add a keymap for toggling the drop-down menu.

**Comment by Bekaboo** [comment]
Ah, I see. Checkout https://github.com/Bekaboo/dropbar.nvim#usage - pick mode and https://github.com/Bekaboo/dropbar.nvim#api - `pick()` function.

**Comment by pwnwriter** [comment]
Hey, thanks for the reponse. 

How'd i know  if dropbar is set or not? 

i wanna write a function that toggles winbar. like if already open then closes, if closed, opens .

For example, here's  a function that i wrote to toggle numbering

```lua
local cmds = { "nu!", "rnu!", "nonu!" }
local current_index = 1

function M.toggle_numbering()
  current_index = current_index % #cmds + 1
  vim.cmd("set " .. cmds[current_index])
end
```

**Comment by pwnwriter** [comment]
As @Bekaboo mentioned, We can set dropbar values, Prooly values, don't know if i'm wrong about the term. 

We have two values nill? which doesn't show anything
```lua
:set winbar=
```
and another one with infos.
```lua
:set winbar=%{%v:lua.dropbar.get_dropbar_str()%}
```

i wanna write mapping to toggle between these cmds .

**Comment by pwnwriter** [comment]
Also, @willothy, what's the use of `vim.v.count` ? 

When i try to print it, i get zero everytime.

**Comment by pwnwriter** [comment]
I've made this workaround, it works pretty well, 
```lua
local winbar_state = 0
function M.toggle_dropbar()
  if winbar_state == 0 then
    vim.cmd "set winbar=%{%v:lua.dropbar.get_dropbar_str()%}"
    winbar_state = 1
  else
    vim.cmd "set winbar="
    winbar_state = 0
  end
end
```

feel free to drop your thoughts tho.

**Comment by willothy** [comment]
> Also, @willothy, what's the use of `vim.v.count` ?
> 
> When i try to print it, i get zero everytime.

`vim.v.count` (or `v:count` in vimscript) is the `count` that can be passed to mappings. Typing a number before a mapping sets `v:count`, which can be used inside the mapping. This works the same was as `3dd` to delete 3 lines; for example, in the mapping I showed above, you would type `3<leader>bs` to open the dropdown for the 3rd symbol in the winbar. 

If no number is typed, `v:count` will be 0. You can also use `vim.v.count` to get a count that will always be 1 instead of 0 when unset.


> Ohh, wow just realized i can actually use alphabets to grab them. Pretty cool.

That's why I check for 0 in the mapping, because passing nil to `.pick()` allows you to use the picker functionality.


> I've made this workaround, it works pretty well,
> 
> ```lua
> local winbar_state = 0
> function M.toggle_dropbar()
>   if winbar_state == 0 then
>     vim.cmd "set winbar=%{%v:lua.dropbar.get_dropbar_str()%}"
>     winbar_state = 1
>   else
>     vim.cmd "set winbar="
>     winbar_state = 0
>   end
> end
> ```
> 
> feel free to drop your thoughts tho.

Thoughts: that's pretty much what I would do, but I think you could simplify it a little. You can use the Lua API to set the winbar option for example, and check its value instead of tracking state:

```lua
function toggle_winbar()
  if vim.o.winbar == "" then
    vim.o.winbar = "%{%v:lua.dropbar.get_dropbar_str()%}"
  else
    vim.o.winbar = ""
  end
end
```
