### ISSUE TITLE
[Bug]: Strange backgrounds appear

### ISSUE THREAD

**Issue by a1401358759** [Bekaboo/dropbar.nvim#118]
### Description

![image](https://github.com/Bekaboo/dropbar.nvim/assets/15830146/0117d0b6-8d94-4f8d-9b63-46bd4086f85b)
Strange backgrounds appear

### nvim version

NVIM v0.10.0-dev-1746+g5651c1ff2

### dropbar.nvim version

2b7c2d53363cb3d93376904dac3ea6d52dd900c5

### Operating system and version

archlinux 6.6.3-arch1-1

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

No desc

### Expected behavior

No desc

### Actual behavior

No desc

**Comment by Bekaboo** [comment]
Duplicate #2.

**Comment by a1401358759** [comment]
Thank you very much for your answer, it has solved my problem!

**Comment by MariaSolOs** [comment]
@Bekaboo since https://github.com/neovim/neovim/issues/26037#issuecomment-1838548013 got merged, can [this bit of code](https://github.com/Bekaboo/dropbar.nvim/blob/e998e4383a84301c0b0aee9f9cf11af7553cb297/lua/dropbar/hlgroups.lua#L126-L140) be removed now?

**Comment by Bekaboo** [comment]
@MariaSolOs I will remove it onve 0.11 is released.

**Comment by MariaSolOs** [comment]
> @MariaSolOs I will remove it once 0.11 is released.

Would you accept a PR that doesn't set up those autocommands when using nightly?
