### ISSUE TITLE
[Bug]: Uses deprecated Nerd Font codepoints

### ISSUE THREAD

**Issue by unphased** [Bekaboo/dropbar.nvim#12]
First off I'd like to congratulate you on this wonderful plugin. I really like every aspect of how it works. Your readme is also epic and goes a lot farther in depth into useful information than any other plugin I have seen yet. Kudos for that.

### Description

My wezterm init shows the following message: 

```
02:35:10.422  WARN   wezterm_font     > No fonts contain glyphs for these codepoints: \u{f668}.
Placeholder glyphs are being displayed instead.
```
All the fonts I have installed are Nerd 3.0+ patched fonts. 

Note if you check these codepoints on here: https://www.nerdfonts.com/cheat-sheet they will say removed, because these codepoints interfere and were incorrectly chosen in the first place. 

### nvim version

n/a

### dropbar.nvim version

n/a

### Operating system and version

n/a

### Minimal config

```Lua
n/a
```

### Steps to reproduce

n/a

### Expected behavior

Do not use the forbidden code points. I believe this is a good tool to look into as it is specifically built for this purpose of finding and fixing these bad code points in your project. https://github.com/loichyan/nerdfix

Realistically the fix is really basic and should be localized to a change in the default symbol table only. 

### Actual behavior

Usage of bad code points shown below:

```
❯ grep -r -P "\x{f668}" ~/.local/share/nvim               
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:          Namespace = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:          Object = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:          Scope = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:          Statement = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:      Namespace = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:      Object = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:      Scope = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/README.md:      Statement = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:        icon = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:      local plain_str = ' |  testing    '
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:        '%%#DropBar#%%* | %%@v:lua.dropbar.on_click_callbacks.buf%d.win%d.fn%d@%%#DropBarIconTest# %%*%%#DropBarNameTest#testing%%*%%X%%#DropBar#    %%*',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:        vim.fn.strdisplaywidth(' |  testing    '),
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:      assert.are.same(' |  t...    ', winbar:cat(true))
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:      assert.are.same(' ', symbol.icon)
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:      assert.are.same(' testing', symbol:cat(true))
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:          '%%@v:lua.dropbar.on_click_callbacks.buf%d.win%d.fn%d@%%#DropBarIconTest# %%*%%#DropBarNameTest#testing%%*%%X',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:        vim.fn.strdisplaywidth(' testing'),
/home/slu/.local/share/nvim/lazy/dropbar.nvim/tests/bar_spec.lua:      assert.are.same(#' testing', symbol:bytewidth())
/home/slu/.local/share/nvim/lazy/dropbar.nvim/doc/dropbar.txt:              Namespace = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/doc/dropbar.txt:              Object = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/doc/dropbar.txt:              Scope = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/doc/dropbar.txt:              Statement = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar/configs.lua:        Namespace = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar/configs.lua:        Object = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar/configs.lua:        Scope = ' ',
/home/slu/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar/configs.lua:        Statement = ' ',
/home/slu/.local/share/nvim/lazy/neo-tree.nvim/lua/neo-tree/defaults.lua:      Object = { icon = "", hl = "Type" },
```
Oh look it seems like neo-tree also has some stale codepoints in it.

**Comment by unphased** [comment]
I think i just saw an update and you just fixed these symbols! Epic

**Comment by Bekaboo** [comment]
Thanks for reporting, that's weird because the nerd font issue is supposed to be fixed in commit 03f6e8635d413805d1143f4a2614c814a4e798d9, will look into this later.

**Comment by unphased** [comment]
The delta I just observed in my lazy.nvim update was

 14¦   │  "dropbar.nvim": { "branch": "master", "commit": "8cb3ab8c74ef1eab1f955fbada186b6a5425de8a" },
   ¦ 14│  "dropbar.nvim": { "branch": "master", "commit": "07ea90ec4f7b2191a53a315335bbefe7716d8e30" },

(bottom line is the new commit)

**Comment by Bekaboo** [comment]
> I think i just saw an update and you just fixed these symbols! Epic

Oops! Good to hear that.
