### ISSUE TITLE
[Feature]: find symbols in `onsails/lspkind.nvim` firstly and fallback to `opts.icons.kinds.symbols` table.

### ISSUE THREAD

**Issue by gh-liu** [Bekaboo/dropbar.nvim#125]
### Problem

Make the symbols same as `onsails/lspkind.nvim`.

### Expected behavior

Maybe add a `opts.icons.kinds.use_lspkind` option in config to find symbols fistly.

**Comment by Bekaboo** [comment]
Hi thanks for your feedback!

I don't use lspkind.nvim, after all, unlike nvim-web-devicons, there are not many icons in lspkind -- you can define the icons yourself or just grab the icons from lspkind.nvim and pass them to `opts.icons.kinds`. Also, notice that dropbar.nvim uses icons that lspkind does not support -- for example, `markdownH1/2/3/4/5/6`, `Null`, `IfStatement`, `WhileStatement`, etc for custom parsers and treesitter parsers, so using lspkind.nvim is not really an option.

**Comment by baco** [comment]
@gh-liu I've found a workaround, if you are still interested:

```lua
local lspkind = require("lspkind")
require("dropbar").setup({
  icons = {
    kinds = {
      symbols = lspkind.presets.codicons,
      dir_icon = "",
    }
  }
})
```

that makes `dropbar` use `lspkind` but you have to manage `lspkind` installation by yourself.

Although it comes with some rendering/overlapping issues, I don't know why:
<img width="564" height="38" alt="Image" src="https://github.com/user-attachments/assets/fe142c14-51ef-4440-92a9-bf1d535da3bd" />

As a reference, this is where I was coming from when replacing `barbecue` with `dropbar`:
<img width="564" height="38" alt="Image" src="https://github.com/user-attachments/assets/92ca9624-fc36-49ca-a2c2-5c4b6319e530" />
