### ISSUE TITLE
[Bug]: Doesn't play nice with the default colorscheme

### ISSUE THREAD

**Issue by seblj** [Bekaboo/dropbar.nvim#138]
### Description

Dropbar doesn't play so nice with the default colorscheme in neovim. I would expect it to at least have the same highlight for all of the different sections. Either make all the folder icons have the background of the other sections, or make all the other sections have the same color as the folders.

![image](https://github.com/Bekaboo/dropbar.nvim/assets/5160701/98fe5cbd-3556-42b8-98a4-6f8becb296fb)

### nvim version

NVIM v0.10.0-dev-2216+g2cd76a758

### dropbar.nvim version

f835519

### Operating system and version

macOS

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

Use the minimal config, and open a file where the dropbar is visible like in the picture in the description

### Expected behavior

I would expect dropbar to play nice with the default colorscheme, and have the same background for all sections. Personally I like it when the dropbar blends in with the background color of `Normal`. However, this is more subjective, and I totally understand if it should stay or be the color that it mostly has for the background. It should at least just be the same background color for the entire bar

### Actual behavior

The folder icons and other text have different backgrounds, and doesn't look as nice as it could have if they are were the same color

**Comment by Bekaboo** [comment]
Duplicate https://github.com/Bekaboo/dropbar.nvim/issues/118. Also you should update your nvim nightly build, the latest version does not have background color.

**Comment by seblj** [comment]
> Duplicate https://github.com/Bekaboo/dropbar.nvim/issues/118. Also you should update your nvim nightly build, the latest version does not have winbar background color.

Sorry for the duplicate issue, but no. The latest build have the same issue
