### ISSUE TITLE
[Bug]: cannot use in active window

### ISSUE THREAD

**Issue by stribor14** [Bekaboo/dropbar.nvim#149]
### Description

I cannot figure why, but if I'm in the same window where I want to use dropbar, selecting it (with mouse or picker), it only flickers on-off. But if I'm in the other window (like neotree or split windows), I can select it with mouse and it works as expected

### nvim version

NVIM v0.10.0-dev

### dropbar.nvim version

f1034cf

### Operating system and version

Ubuntu20.04

### Minimal config

```Lua
--- don't know :(

I took latest kickstart.nvim and I'm setting it up (still a newbie)
```

### Steps to reproduce

--

### Expected behavior

If I click dropbar with mouse (or select it with picker), I expect floating elements to stay so I could use them

### Actual behavior

They flicker on-off quickly

**Comment by Bekaboo** [comment]
Cannot reproduce. A minimal repro config might help, please refer to the issue template for the minimal config to start with.
