### ISSUE TITLE
[Feature]: Disable symbols

### ISSUE THREAD

**Issue by marcelarie** [Bekaboo/dropbar.nvim#151]
### Problem

I want to disable all the symbols and lsp sometimes, is there a way to do this directly via the config?

### Expected behavior

have a way disabling the symbols in the config:
```lua
opts = {
  sources = {
    lsp = {
       enabled = false  
    },
    treesitter = {
       enabled = false 
    }
  },
}
```

This is just an example, the opts proper structure might be another one.

**Comment by Bekaboo** [comment]
You can disable all sources with

```lua
require('dropbar').setup({
  bar = { sources = {} },
})
```

But why would you use this plugin in the first place if you want to disable all sources/symbols?

**Comment by marcelarie** [comment]
A ok, I want to enable/disable them temporary via a command, sometimes the symbols are too distracting.

Thanks!

**Comment by marcelarie** [comment]
I just tried and this disables everything. I would like to disable only these ones:

<img width="605" alt="Screenshot 2024-04-09 at 10 37 43" src="https://github.com/Bekaboo/dropbar.nvim/assets/62728887/3852e2ad-2c7a-470c-a4ec-fd6d54e0d2e0">

**Comment by Bekaboo** [comment]
@marcelarie Have you tried this?

```lua
local sources = require('plugin.winbar.sources')
require('dropbar').setup({
  bar = { sources = { sources.path } },
})
```
