### ISSUE TITLE
[Bug]: Unknown option 'winfixbuf'

### ISSUE THREAD

**Issue by nguyenxuanhung-rightsvn** [Bekaboo/dropbar.nvim#155]
### Description

When i use pick mode `require('dropbar.api').pick()`, i got an error as shown in the image bellow
<img width="1439" alt="Screenshot 2024-05-05 at 16 24 53" src="https://github.com/Bekaboo/dropbar.nvim/assets/80736507/b6042acd-099e-4f70-a4d1-43e776ada2f1">

I tried updating droppbar.vim by `:Lazy update droppbar.nvim` but couldn't resolve the problem.

### nvim version

v0.10.0-dev-1744+g0d885247b

### dropbar.nvim version

3dd8edb

### Operating system and version

MacOS 14.2.1 (23C71)

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

3. use `require('dropbar.api').pick()`

### Expected behavior

If I use `require('dropbar.api').pick()`, It doesn't error

### Actual behavior

Display an error as shown in the image bellow
<img width="1439" alt="Screenshot 2024-05-05 at 16 24 53" src="https://github.com/Bekaboo/dropbar.nvim/assets/80736507/b6042acd-099e-4f70-a4d1-43e776ada2f1">

### Additional information

Please help me

**Comment by Bekaboo** [comment]
You should upgrade your nvim installation.
