### ISSUE TITLE
[Bug]: nvchad?black background

### ISSUE THREAD

**Issue by Miguerfi** [Bekaboo/dropbar.nvim#156]
### Description

when i'm using nvchad the backgroundo of someparts are black

![image](https://github.com/Bekaboo/dropbar.nvim/assets/91486755/5ed3b7a1-5cf5-478b-9f11-0f11e86608a4)

### nvim version

neovide 0.12.2

### dropbar.nvim version

3dd8edba9f9eeb129db269dd57ef6c0427b7ad9d

### Operating system and version

 6.8.9-arch1-1 

### Minimal config

```Lua
vim.ui.select = require('dropbar.utils.menu').select
```

### Steps to reproduce

1 - install the plugin; 2 - start neovim, 3 - see the error.

### Expected behavior

the background be the same from current buffer

### Actual behavior

background not being the same of current buffer

**Comment by Bekaboo** [comment]
Duplicate https://github.com/Bekaboo/dropbar.nvim/issues/118
