### ISSUE TITLE
[Feature]: Highlight group for menu

### ISSUE THREAD

**Issue by schizophrenical** [Bekaboo/dropbar.nvim#16]
### Problem

As I understand it, `dropbar` follow the `WinBar` highlight group so changing the colors for `WinBar` will also reflect in `dropbar`.

This is working well as show below:
![Screenshot_2023-06-01-20-48-02_3440x1440](https://github.com/Bekaboo/dropbar.nvim/assets/117723239/77eed2f3-ded7-4ea9-a66c-c081e99a8731)

Note that, I have a slightly different foreground color in `WinBar` compared to `Normal`. 

However, for the menu items, it would be a 'nice-to-have' addition if the menu items also follows the `WinBar` highlights groups.

Below is a capture of the menu items:
![Screenshot_2023-06-01-20-48-20_3440x1440](https://github.com/Bekaboo/dropbar.nvim/assets/117723239/fae51701-92be-4d45-adf5-57afb021b60a)

To further demonstrate, I have temporarily changed `WinBar` and  `WinBarNC` to red and clicked on the winbar to reveal the menu items:
![Screenshot_2023-06-01-20-58-52_3440x1440](https://github.com/Bekaboo/dropbar.nvim/assets/117723239/6bde7e77-2a4c-48c9-bde2-a1564b884cac)

### Expected behavior

It would be a 'nice-to-have' if we have a highlight group for the menu items buffer. OR;
Make the menu items buffer follow `WinBar` highlight group for consistency.

**Comment by akinsho** [comment]
I was doing some digging around, to find a highlight group to change the background of the actual menu windows themselves. I thought `DropBarMenuNormalFloat` would change the background of the whole window but seems to only change each particular element. By default the `NormalFloat` usually applies to the entire float. 

Is there a way to change the highlight for the entire window itself?

**Comment by akinsho** [comment]
Hi @Bekaboo,

I was thinking more the entire window itself i.e. if you wanted to change the colour of an entire floating window. Not just parts of the text

**Comment by Bekaboo** [comment]
@akinsho 

> the colour of an entire floating window

Do you mean the background color of the menu? Currently no special highlight groups are set for that, but I think it can be done using `'winhl'` if one wants to remap the background highlights.

**Comment by akinsho** [comment]
@Bekaboo yep I mean the background colour of the menu, essentially the same way you can tweak the background of `cmp`, `telescope`, `lazy` etc. just the standard `NormalFloat` winhighlight for the opened windows. Some plugins offer config via the winhl others map the winhighlight to plugin specific variants e.g. `vim.wo.winhlight:append({ NormalFloat = 'DropbarCustomBg' })` I was essentially trying to figure out if that already existed as a highlight group. As you say it can be done through the `winhl` but is there an option for this somewhere? The docs/README don't mention `winhl`

**Comment by Bekaboo** [comment]
@akinsho Added `hl-DropBarMenuNormalFloat` and `hl-DropBarMenuFloatBorder`.

**Comment by akinsho** [comment]
Awesome works great thanks 🙌🏾
