### ISSUE TITLE
[Feature]: Not compatible background color between right arrow symbol and text?

### ISSUE THREAD

**Issue by linrongbin16** [Bekaboo/dropbar.nvim#161]
### Problem

Some highlightings (sorry I'm not sure which one) do not work quite fit with [OceanNext](https://github.com/mhartington/oceanic-next) colorscheme. See picture below:

<img width="1920" alt="image" src="https://github.com/Bekaboo/dropbar.nvim/assets/6496887/e930693c-6e3f-4dd1-a213-3bd37efefb8d">

You can see, the background color from the right arrow symbol (`>`) to the icon symbol, is not the same with the text (`.github`, `workflows`, `ci.yml`, etc) background.

### Expected behavior

I guess it's some highlightings missing in `OceanNext` colorscheme. But how could we configure to fix it?

In another colorscheme [tokyonight](https://github.com/folke/tokyonight.nvim), there's no such issue:

<img width="1920" alt="image" src="https://github.com/Bekaboo/dropbar.nvim/assets/6496887/99e17ab9-eb08-4d8c-8aa5-69e7a075d108">

**Comment by Bekaboo** [comment]
Duplicate https://github.com/Bekaboo/dropbar.nvim/issues/118
