### ISSUE TITLE
[Feature]: Synchronize the enabled state of two windows when `scrollbind`

### ISSUE THREAD

**Issue by ofseed** [Bekaboo/dropbar.nvim#165]
### Problem

When `scrollbind` is set, we expect that every line of the two windows has a line-to-line relationship, but if one window's winbar is enabled while the other is not, we lose the relationship.

For example, for git blame plugins, the right window shows the file, and the left window shows its corresponding blame information for every line. The line-to-line relation will be broken if the right window has a `winbar` while the left window does not.

* fugitive.vim `:Git blame`
![image](https://github.com/Bekaboo/dropbar.nvim/assets/61115159/39287da4-7cec-436c-acab-8d0c3477a8c2)

* gitsigns.nvim `:Gitsigns blame`
![image](https://github.com/Bekaboo/dropbar.nvim/assets/61115159/739605a7-301f-43f1-a35c-6a1ef4496d6a)

### Expected behavior

If one of the two `scrollbind` windows has the dropbar enabled, the other must be enabled too.

**Comment by Bekaboo** [comment]
Scroll-bind window synchronization should be handled by nvim IMO. However, as a workaround, you can use the following autocmd to fix this:

```lua
vim.api.nvim_create_autocmd('FileType', {
  desc = 'Set buffer-local options for fugitive blame buffers.',
  group = vim.api.nvim_create_augroup('FugitiveSettings', {}),
  pattern = 'fugitive blame',
  callback = function()
    local win_alt = vim.fn.win_getid(vim.fn.winnr('#'))
    vim.opt_local.winbar = vim.api.nvim_win_is_valid(win_alt)
        and vim.wo[win_alt].winbar ~= ''
        and ' '
      or ''

    vim.opt_local.number = false
    vim.opt_local.signcolumn = 'no'
    vim.opt_local.relativenumber = false
  end,
})
```
