### ISSUE TITLE
[Feature]: Only open selection, don't change CWD

### ISSUE THREAD

**Issue by Ajaymamtora** [Bekaboo/dropbar.nvim#166]
### Problem

When I manually click and item using the dropdowns from the dropbar, it changes my CWD. Is there any way to prevent this?

### Expected behavior

Just open the file/symbol - don't change the cwd.

**Comment by Bekaboo** [comment]
This should be considered as a bug. Please open a bug report and provide minimal steps to reproduce. Thanks!

**Comment by Bekaboo** [comment]
@Ajaymamtora Is this still happening to you? If not I am going to close this issue.
