### ISSUE TITLE
[Bug]: Function get_symbols has error on Windows

### ISSUE THREAD

**Issue by MaoX-Yu** [Bekaboo/dropbar.nvim#174]
### Description

https://github.com/Bekaboo/dropbar.nvim/blob/c53d1d312407927903f0ce4bb504e25113641989/lua/dropbar/sources/path.lua#L177-L181
sometimes, `current_path` will start with `c:` but `root` start with `C:` like this
![image](https://github.com/user-attachments/assets/dc0263a4-c3d7-4c4b-ab64-d7d235834b98)
it makes `current_path ~= root` and loop continue

### nvim version

NVIM v0.11.0-dev-608+g9d74dc3ac

### dropbar.nvim version

c53d1d3

### Operating system and version

Windows 10

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

try open file in nvim

### Expected behavior

![image](https://github.com/user-attachments/assets/0f490447-16f8-4d2e-986a-2adf6371004c)
start with src

### Actual behavior

![image](https://github.com/user-attachments/assets/9e83c2ee-f091-4022-873f-1a62cfb503fc)
start with Users

**Comment by Bekaboo** [comment]
Not on windows so cannot test nor fix this bug. PR welcome!
