### ISSUE TITLE
[Bug]: attempt to index global '_winbar' (a nil value)

### ISSUE THREAD

**Issue by Aphosis** [Bekaboo/dropbar.nvim#177]
### Description

Hi !

First of all thanks for the awesome plugin, I don't use it that often but when I do need it it's a life saver.

Since 0edf5d5025ef1a1ad3574237757368b1372bc4cb I get the following error when opening a file:

```
E5108: Error executing lua [string "v:lua"]:1: attempt to index global '_winbar' (a nil value)
stack traceback:
        [string "v:lua"]:1: in main chunk
```

I don't know if this was intended but the lua callback was changed during the refactor, from `lua.dropbar.get_dropbar_str()` to `lua._winbar.get_winbar()`.

I locally changed it back to `lua.dropbar.get_dropbar_str()` and now everything seems to work again.

I don't know if this was an intended change and another update wasn't pushed maybe ? Or it's using a new API in neovim 0.11 ?

I'm also not pinned to a specific version of the plugin so maybe I should stick to a release and not update to specific commits ?

Anyway I thought I'd let you know just in case, have a good day !

### nvim version

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### dropbar.nvim version

489b08a

### Operating system and version

CentOS Linux release 7.6.1810 (Core)

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

1. Copy the minimal config to init.lua
2. I ran `nvim` then `:e README.md` in this repo
3. You can see the aforementioned error in the message bar

### Expected behavior

No error

### Actual behavior

There is an error and the winbar displays 0

**Comment by farhaddaei** [comment]
I encountered the same problem and temporarily checked out commit d26bf92 to resolve the issue. Here is my NVIM version:
```bash  
$ nvim --version  
NVIM v0.11.0-dev  
Build type: RelWithDebInfo  
LuaJIT 2.1.0-beta3  
Run "nvim -V1 -v" for more info  
```

**Comment by tan-wei** [comment]
Met the same issue.

**Comment by mgastonportillo** [comment]
Sounds like the global is missing. Until fixed, it's probably a good idea to stick to [`d26bf92`](https://github.com/Bekaboo/dropbar.nvim/commit/d26bf92161cd70e049dc138b44ffa0246dbf7178), as the pals suggested.

**Comment by Bekaboo** [comment]
Sorry for the mistake. Should be fixed in latest commit.
