### ISSUE TITLE
[Feature]: support of `mini.icons`

### ISSUE THREAD

**Issue by mathjiajia** [Bekaboo/dropbar.nvim#179]
### Problem

Currently only support `nvim-web-devicons`
it will be great to support `mini.icons` as well

ref: https://github.com/echasnovski/mini.icons

### Expected behavior

display the correct icon/hl when `mini.icons` is available`

**Comment by Bekaboo** [comment]
I think you can use `MiniIcons.mock_nvim_web_devicons()`, as mentioned in their doc.

**Comment by mathjiajia** [comment]
why not to have a ‘native’ support?

**Comment by zahidislm** [comment]
`MiniIcons.mock_nvim_web_devicons()` is meant to be a stop-gap method until plugin authors are able to update their plugins to explicitly add support. Since the mock function adds quite a bit overhead, is it possible to natively add support? I can submit a PR if it'll help.
