### ISSUE TITLE
[Bug]: for c++, if_statement, for_statement, etc, are not shown in the bar

### ISSUE THREAD

**Issue by ktkimit** [Bekaboo/dropbar.nvim#184]
### Description

Drop bar is missing some treesitter node for .cpp (or .h) files, for example, "for_statement" is not shown in the bar as described below.
![image](https://github.com/user-attachments/assets/bc8741f0-d68c-447e-a855-137985f879f2)

### nvim version

0.10.1

### dropbar.nvim version

cc9e637

### Operating system and version

Linux 6.3.2-arch

### Minimal config

```Lua
return
  {
    'Bekaboo/dropbar.nvim',
    -- optional, but required for fuzzy finder support
    dependencies = {
      'nvim-telescope/telescope-fzf-native.nvim'
    }
  }
```

### Steps to reproduce

Saved dropbar.lua
Restarted nvim
Opened a cpp file

### Expected behavior

Any treesitter nodes (listed in `opts.sources.treesitter.valid_types`)  should be shown in the bar.

### Actual behavior

Some treesitter nodes are missing in the bar (for example for_statement).

### Additional information

No additional information.

**Comment by Bekaboo** [comment]
Not a bug -- by default the lsp source takes precedence -- if the lsp source has symbols we don't use treesitter source. Try disabling the lsp source or put it after the treesitter source.

**Comment by ktkimit** [comment]
Thank you for a quick reply!
