### ISSUE TITLE
[feature] add ability to disable file path display

### ISSUE THREAD

**Issue by melsiir** [Bekaboo/dropbar.nvim#197]
### Problem

dropbar is very good and fast compared to barbecue but the the problem is that the winbar become too messy when in small screen even the transcating wont help 
![Screenshot_٢٠٢٤١١١٥-١٢١٤٠٨_Termux](https://github.com/user-attachments/assets/2a562ec2-0268-4cbe-b5b7-74e73ee7037d)

i hope to see winbar have the options to  transcating the left side always instead of trying to fit the all the components into the screen which effect the readabilty of the winbar
i tried to mess reletive to disable the plugin from showing the file path but no luck
in barbecue there are this simple option to do the job
show_dirname = false
i think this option should be added to dropbar.nvim

### Expected behavior

hide file path completely to fit in small screen

**Comment by RenGeng** [comment]
There's a config here https://github.com/Bekaboo/dropbar.nvim/discussions/132

**Comment by Bekaboo** [comment]
You can disable the path source by

```lua
require("dropbar").setup({
	bar = {
		sources = function(buf, _)
			local sources = require("dropbar.sources")
			local utils = require("dropbar.utils")
			if vim.bo[buf].ft == "markdown" then
				return { sources.markdown }
			end
			if vim.bo[buf].buftype == "terminal" then
				return { sources.terminal }
			end
			return { utils.source.fallback({ sources.lsp, sources.treesitter }) }
		end,
	},
})
```

See https://github.com/Bekaboo/dropbar.nvim?tab=readme-ov-file#sources.
