### ISSUE TITLE
[Bug]: Dropbar not showing

### ISSUE THREAD

**Issue by ShelpAm** [Bekaboo/dropbar.nvim#199]
### Description

When I open a `.cpp` file, the plugin doesn't render anything to the screen. But when I open a `.lua` file or `.md` file, it works normally.

Additionally, if I load a `.cpp` file after loading a `.lua` file, it works as expected, which is confusing...

### nvim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1720049189 Run "nvim -V1 -v" for more info

### dropbar.nvim version

321cbc7

### Operating system and version

Fedora 6.11.10-300.fc41.x86_64

### Minimal config

```Lua
return {
    {
        'Bekaboo/dropbar.nvim',
        lazy = false,
        -- optional, but required for fuzzy finder support
        dependencies = {
            'nvim-telescope/telescope-fzf-native.nvim',
            build = 'make'
        },
        config = function()
            local dropbar_api = require('dropbar.api')
            vim.keymap.set('n', '<Leader>;', dropbar_api.pick, { desc = 'Pick symbols in winbar' })
            vim.keymap.set('n', '[;', dropbar_api.goto_context_start, { desc = 'Go to start of current context' })
            vim.keymap.set('n', '];', dropbar_api.select_next_context, { desc = 'Select next context' })
        end
    }
}
```

Btw, I'm also using the following config for clangd:
```lua
local function default_on_attach( --[[client]] _, bufnr)
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local bufopts = { noremap = true, silent = true, buffer = bufnr }
    local keymaps = require('user.core.keymaps')
    keymaps.map('n', '<leader>rn', vim.lsp.buf.rename, { desc = '[R]e[n]ame', unpack(bufopts) })
    keymaps.map('n', '<leader>ca', vim.lsp.buf.code_action, { desc = '[C]ode [A]ction' })
    keymaps.map('n', 'gd', vim.lsp.buf.definition, { desc = '[G]oto [D]efinition', unpack(bufopts) })
    keymaps.map('n', 'gh', vim.lsp.buf.hover, { desc = '[G]oto [H]over', unpack(bufopts) })
    keymaps.map('n', 'gi', vim.lsp.buf.implementation, { desc = '[G]oto [I]mplemetation', unpack(bufopts) })
    keymaps.map('n', 'gr', vim.lsp.buf.references, { desc = '[G]oto [R]eference', unpack(bufopts) })
    keymaps.map('n', '<leader>d', '<Cmd>Telescope lsp_document_symbols<CR>', bufopts)
    -- There has been `K` for hover, so disabling this
    -- keymaps.map('n', '<leader>K', vim.lsp.buf.hover, bufopts)
end

require('lspconfig').clangd.setup {
    -- Add additional capabilities supported by nvim-cmp
    capabilities = require('cmp_nvim_lsp').default_capabilities(),
    on_attach = default_on_attach,
    cmd = {
        "clangd",
        -- "-j=8",
        "-header-insertion=never",
    },
}
```
Although I commented it out, it didn't make any difference...

### Steps to reproduce

I don't know how to load the minimal config, because when I entered `nvim --clean -u minimal.lua`, it reported:
```
Error detected while processing /home/shelpam/minimal.lua:
E5113: Error while calling lua chunk: /home/shelpam/minimal.lua:1: module 'lazy' no
t found:
...
```

Maybe you can help me get this minimal config to work...

### Expected behavior

The plugin should render dropbar normally.

### Actual behavior

The plugin doesn't render the dropbar.

**Comment by ShelpAm** [comment]
Oh I just found that when I saved the buffer (enter `:w`), the dropbar showed up. If I missed something?

**Comment by Bekaboo** [comment]
You can use the provided minial config in the issue template as a stating point for your reprodce. I cannot help you debug your whole config.

Also, make sure you have installed treesitterparser or started lsp properly when loading a cpp file because dropbar uses either of them as the symbol source.

**Comment by ShelpAm** [comment]
> You can use the provided minial config in the issue template as a stating point for your reprodce. I cannot help you debug your whole config.

Ok, I'll try that.

> Also, make sure you have installed treesitter parser or started lsp properly when loading a cpp file because dropbar uses either of them as the symbol source.

How can I know if the plugin is relying on a treesitter parser or a lsp?

**Comment by ShelpAm** [comment]
After adding treesitter plugin into dependencies, it works great!

Thanks for your help!
