### ISSUE TITLE
[Feature]: Add support for underline

### ISSUE THREAD

**Issue by Racle** [Bekaboo/dropbar.nvim#2]
### Problem

Why? 
Underline separates code and top bar nicely. This also prevents to mistaking top bar as part of your code.

[Kitty](https://github.com/kovidgoyal/kitty) terminal has built-in support for this as well neovim.

### Expected behavior

Result should look something like this.
![image](https://github.com/Bekaboo/dropbar.nvim/assets/759091/1b71dbff-9d33-4e38-9afa-ddfbf7f4be46)

This is archived with [lspsaga.nvim](https://github.com/nvimdev/lspsaga.nvim) and with [my custom config](https://github.com/Racle/dotfiles/blob/507fabae6ea6dbc097ffb950ec53f3d1f9b3426c/neovim/.config/nvim/lua/plug-config/lspsaga.lua#L35-L71) to set underline and correct background color to match my "tab" bar (and keep icon colors correct).

**Comment by Bekaboo** [comment]
In dropbar.nvim symbols (a symbol has its name, icon, their corresponding highlights, and many other information, see [`dropbar_symbol_t`](https://github.com/Bekaboo/dropbar.nvim#dropbar_symbol_t) and symbols are provided by [sources](https://github.com/Bekaboo/dropbar.nvim#dropbar_source_t), so I think what you can do is to create your custom sources with modified highlights and feed them to the winbar, like what you did in your config for lspsaga:

```lua
local sources = require('dropbar.sources')

require('dropbar').setup({
  bar = {
    sources = {
      -- Hijack the default path source
      {
        get_symbols = function(buf, cursor)
          local symbols = sources.path.get_symbols(buf, cursor)
          for _, symbol in ipairs(symbols) do
            symbol.name_hl = ...
            symbol.icon_hl = ...
          end
        end,
      }
      -- Hijack other sources ...
    }
  }
})
```

**Comment by Bekaboo** [comment]
> services > db is missing after applying this (very simplified) config.

That is expected because you don't include the lsp source... The snippet I gave above is just a minimal example, you might want to check the [doc](https://github.com/Bekaboo/dropbar.nvim#bar) to see what sources you are going to include.

>  lspsaga winbar is more colorful (which I personally like)

Currently all builtin sources of dropbar.nvim does not set hlgroups for the name (text part) of the symbols, so they are just highlighted with `'WinBar'` and `'WinBarNC'`, personally I prefer this way because in this way I tell symbol names from kinds (icons) more easily. To make the names of symbols highlighted in the same color as that of the icons, set `symbol.name_hl` to equal to `symbol.icon_hl`.

**Comment by IvarWithoutBones** [comment]
I noticed the solution posted above doesn't work anymore, so in case anyone else is looking to change the background color of the bar I thought I'd post my (slightly adapted) version:
```lua
-- Modified version of https://github.com/Bekaboo/dropbar.nvim/issues/2#issuecomment-1568244312, thanks!
local function bar_background_color_source()
    local function set_highlight_take_foreground(opts, source_hl, target_hl)
        if target_hl == nil then target_hl = source_hl end
        local fg = vim.fn.synIDattr(vim.fn.synIDtrans(vim.fn.hlID(source_hl)), "fg#")
        if fg == "" then
            vim.api.nvim_set_hl(0, target_hl, opts)
        else
            vim.api.nvim_set_hl(0, target_hl, vim.tbl_extend("force", opts, { fg = fg }))
        end
    end

    local function color_symbols(symbols, opts)
        for _, symbol in ipairs(symbols) do
            local source_hl = symbol.icon_hl
            symbol.icon_hl = "DropbarSymbol" .. symbol.icon_hl
            symbol.name_hl = symbol.icon_hl
            set_highlight_take_foreground(opts, source_hl, symbol.icon_hl)
        end
        return symbols
    end

    return {
        get_symbols = function(buf, win, cursor)
            -- Use the background of the WinBar highlight group
            local opts = { bg = vim.fn.synIDattr(vim.fn.synIDtrans(vim.fn.hlID("WinBar")), "bg#") }
            set_highlight_take_foreground(opts, "DropBarIconUISeparator")
            set_highlight_take_foreground(opts, "DropBarIconUIPickPivot")

            local sources = require('dropbar.sources')
            if vim.bo[buf].ft == "markdown" then
                return color_symbols(sources.markdown.get_symbols(buf, win, cursor), opts)
            end
            if vim.bo[buf].ft == "terminal" then
                return color_symbols(sources.terminal.get_symbols(buf, win, cursor), opts)
            end

            for _, source in ipairs({ sources.lsp, sources.treesitter }) do
                local symbols = source.get_symbols(buf, win, cursor)
                if not vim.tbl_isempty(symbols) then
                    return color_symbols(symbols, opts)
                end
            end
            return {}
        end
    }
end

require("dropbar").setup({
    bar = {
        sources = function(_, _)
            return { bar_background_color_source() }
        end
    },
})
```
It takes the background from the `WinBar` highlight group, so just configure that to update it. It should be simple to add an underline to this if you're so inclined.
