### ISSUE TITLE
[Feature]: Allow option to change colors of dropbar text

### ISSUE THREAD

**Issue by rrojan** [Bekaboo/dropbar.nvim#207]
### Problem

Currently the colors that are appearing for folders in the dropbar are too bright and I ideally want a way to change them.

![image](https://github.com/user-attachments/assets/21b5e948-c2be-4a4c-856f-feed6a4b44d7)

### Expected behavior

Is there a way to change the colors of folder text like "nvim", ".config", etc in my regard?

**Comment by Bekaboo** [comment]
By default dropbar does not set the color for the names of the symbols, see https://github.com/Bekaboo/dropbar.nvim?tab=readme-ov-file#highlighting. What is the colorscheme you are using? 

I suggest you either
1. configure/change your colorscheme to your like, or
2. manually override hightlight groups `DropBarKindFile` or `DropBarKindFolder` **after** loading your colorscheme using `vim.api.nvim_set_hl()`

If the above does not work, you can raise and issue at your colorscheme's repo.
