### ISSUE TITLE
[Bug]: Confusing drop down menu position if click with a mouse

### ISSUE THREAD

**Issue by xlucn** [Bekaboo/dropbar.nvim#37]
### Description

The current behavior that the drop down menu follows the mouse click position will sometimes be confusing and misleading. I would propose to switch or an option to position the drop down menu relative to the component when clicked, instead of mouse position.

### nvim version

v0.10.0-dev-411+g9dd48f783

### dropbar.nvim version

9c482d3

### Operating system and version

ArchLinux 6.3.5-arch1-1

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

1. Use the minimal configuration above to setup a clean instance.
2. Edit a file, say my nvim configuration lua script
3. Click anywhere of a component in the winbar
4. See the drop down menu positioned relative to the mouse

### Expected behavior

The drop down menu is aligned with the component **on the left side**, like how vscode does
![Screenshot_2023-06-15_12-36-34](https://github.com/Bekaboo/dropbar.nvim/assets/12032219/d1385998-b375-44e2-8729-00389722a3a3)

### Actual behavior

The drop menu follows the mouse click position.

The problem is, if I click near the end of the component, the drop down menu will almost align with the next-level component, which is confusing and misleading. In this screenshot is when I click on the 'i' in 'nvim':

![Screenshot_2023-06-12_16-16-33](https://github.com/Bekaboo/dropbar.nvim/assets/12032219/24d5badf-1a6b-428d-882e-b24897873e3d)

The 'ex', 'vim', 'nvim' folders should be on the same level as 'nvim', which I clicked on. However, now they appear perfectly aligned with the subfolder 'lua'. Sometimes, this behavior tricks me to think the drop down menu is on the wrong level.

**Comment by Bekaboo** [comment]
Hi, thanks for reporting!

> The current behavior that the drop down menu follows the mouse click position

Have you tried `require('dropbar.api').pick()`? This allows you to pick a component in the winbar using your keyboard and the menu will be placed according the position of the component in the winbar.

If you use a mouse to click a component, then it is natural for the menu to follow the mouse position. That being said, I will try to refactor the classes structures to make it easier for users to find out with component is clicked in the winbar so that they can adjust `opts.menu.win_configs.col` accordingly.

**Comment by xlucn** [comment]
> Have you tried require('dropbar.api').pick()?

Yes, I knew that and it works well!

> If you use a mouse to click a component, then it is natural for the menu to follow the mouse position.

That might depend. If you Google "drop down menu" images, in most cases of various platforms, the menu actually do not follow the click/touch position. I think the idea is, the drop down menu provides options for, and thus is related more closely to, the object itself than where you want to click it.

Of course, this might boil down to a personal preference. It won't be an issue if not so many users are bothered by it.

**Comment by calops** [comment]
> If you use a mouse to click a component, then it is natural for the menu to follow the mouse position.

I think the general consensus on this is that when clicking *a button*, the resulting menu should be aligned with the button, not the cursor. The opposite is true for the *context* menu, using right click.
