### ISSUE TITLE
[Bug]: attempt to index  field 'uv' (a nil value)

### ISSUE THREAD

**Issue by unphased** [Bekaboo/dropbar.nvim#44]
### Description

I thought something must be messed up because I think `vim.uv` is an api that should always be available. 

However I did try commenting out dropbar.nvim and it did fix the issue. 

So now I don't know what to think and it is hard to figure out what `vim.uv` is supposed to be, if it is always nil and dropbar is somehow the only plugin i use that uses it. 

### nvim version

NVIM v0.10.0-dev-1780+g68e2d7229-Homebrew Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-68e2d72/share/nvim"

### dropbar.nvim version

2cc0381

### Operating system and version

macos 12.6.2

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

Open any file with `nvim -u minimal-dropbar-debug.lua` with the default minimal config as above. it reproduces for me. 

### Expected behavior

no error preventing usage of nvim

### Actual behavior

error repeats incessantly

**Comment by Bekaboo** [comment]
You should update your nvim version, see https://github.com/neovim/neovim/pull/22846.

**Comment by unphased** [comment]
Thanks, I did just find https://github.com/neovim/neovim/pull/22846 independently and I'm reading it now, but, I use nvim across like 5 computers and I don't think it's really fair to just silently break things like this and require people like me to do a whole bunch of work just to get things up and running again. Maybe the ecosystem doesn't really have a good version management solution but breaking stuff this hard seems like itll add too much friction for casual users. 

Can't we at least add a check for the api and maybe disable some functionality if necessary? Print a useful error message at least.

**Comment by Bekaboo** [comment]
@unphased I think you can pin the plugin to a specific verdion if you are using packer or lazy.

Strickly speaking it is nvim that introduces this breaking change in their API so this is out of my control -- if I stick to the old API, I believe it will affect a larger amount users.

**Comment by unphased** [comment]
I am pretty sure the linked PR clearly states that vim.loop is set to be a reference to vim.uv, in case that's what you're talking about. it shouldnt be a breaking change

**Comment by Bekaboo** [comment]
@unphased Thank for the remind, yeah it seems that `vim.loop` will continue to work currently although it is flagged as deprecated. However I have no interest in converting from using `vim.uv` to `vim.loop`. I can use the commit b00ede8 to avoid the issue if you have problem updating your nvim version.

**Comment by unphased** [comment]
Would you accept a PR if I make one to switch vim.loop calls to vim.uv?

**Comment by Bekaboo** [comment]
Sorry I won't accept a PR that uses deprecated API.
