### ISSUE TITLE
[Feature]: Add a `latest` tag to the latest release

### ISSUE THREAD

**Issue by calops** [Bekaboo/dropbar.nvim#48]
### Problem

Currently in a package manager, we only have the option of either pinning a stable release without knowing when a new one appears, or following the `main` branch which is occasionally broken, like right now (which is fine, it's to be expected).

### Expected behavior

Having a blanket `latest-release` tag that is always moved to the latest release would allow us to stay updated without having to suffer the instabilities of the `main` branch.

Alternatively, adopting a workflow where everything is done in a `dev` branch and only stable releases are merged into `main` would achieve the same result.

**Comment by Bekaboo** [comment]
> Having a blanket latest-release tag that is always moved to the latest release would allow us to stay updated without having to suffer the instabilities of the main branch.

Good idea, would you create a pull request to add a github workflow so that we can automate this process?
