### ISSUE TITLE
[Question]: How to disable boldness by default?

### ISSUE THREAD

**Issue by MariaSolOs** [Bekaboo/dropbar.nvim#61]
First of all, amazing plugin!

I have an issue though that's probably just me missing something: I want everything (the folder names and each symbol) to not be bold, but I just haven't been able to. I've tried setting `opts.bar.hover = false`, setting `DropBarMenuHoverSymbol = { bold = false }` in my colorscheme (it seems like this is the only group that sets `bold = true`) but it's still not working. The boldness does go away _after_ clicking with one of the sections at least once.

<img width="620" alt="image" src="https://github.com/Bekaboo/dropbar.nvim/assets/62502207/6bee50ab-8c68-4b9d-ab30-ac5d3f1ebbe3">

**Comment by Bekaboo** [comment]
Please check if `hl-WinBar` is bold.
