### ISSUE TITLE
How to create a keyboard mapping for a "click at" behavior?

### ISSUE THREAD

**Issue by MariaSolOs** [Bekaboo/dropbar.nvim#66]
Not a bug and I'm not sure if this is actually already implemented, but the thing is that I want to map `'o'` to a "jump and close" action, similar to what happens when left-clicking once but with the keyboard.

I've tried the following but it isn't working :(
```lua
['o'] = function()
  local menu = api.get_current_dropbar_menu()
  if not menu then
    return
  end
  local cursor = vim.api.nvim_win_get_cursor(menu.win)
  menu:click_at({ cursor[1], cursor[2] }, nil, 1, 'l')
end
```

**Comment by Bekaboo** [comment]
I believe you can press `<CR>` to "click" on an item in the menu

**Comment by MariaSolOs** [comment]
> I believe you can press `<CR>` to "click" on an item in the menu

It’s not the same. `<CR>` expands the component if its clickable, but I want to jump to the selected component even if it has children(this is what left clicking does)

**Comment by Bekaboo** [comment]
@MariaSolOs Try pressing `<CR>` on the item you would like to jump to, instead of on the indicator (the small arrow).

**Comment by Bekaboo** [comment]
Then try to get the second component of a menu entry then "click" on it (`dropbar_menu_entry_t.components`), for more information please refer to the document and the source code.

**Comment by MariaSolOs** [comment]
Alright, thanks. An example would have been helpful, but I understand you’re busy. Thanks.

**Comment by Bekaboo** [comment]
You are welcome, don't hesitate to ask if you still find it hard to remap the key.

**Comment by sahinakkaya** [comment]
Hey @MariaSolOs I've improved your mapping further by adding an actual `h` mapping. You may want to check it out: https://github.com/Bekaboo/dropbar.nvim/issues/160

**Comment by MariaSolOs** [comment]
@sahinakkaya thanks, but I'm not using this plugin anymore.
