### ISSUE TITLE
[Feature]: Detach from the buffer when `general.enable` returns false

### ISSUE THREAD

**Issue by lopi-py** [Bekaboo/dropbar.nvim#70]
### Problem

When using [trouble](https://github.com/folke/trouble.nvim), seems like `general.enable` gives a false positive (I also tried with my own function) so dropbar is attached, but on later calls, `general.enable` returns false
![image](https://github.com/Bekaboo/dropbar.nvim/assets/70210066/10d58eda-86d6-4a62-9f60-87a3d79c8526)

### Expected behavior

The dropbar should be detached (if attached first) from the given buffer if `general.enable` returns false

**Comment by Bekaboo** [comment]
No, because that can accidently disable winbar set by other plugins, see #9. Instead you should improve the `enable` function in your config so that dropbar won't attach to Trouble windows. Let me know if you find it difficult to implement.

**Comment by lopi-py** [comment]
Seems like trouble first emits an empty buffer (no bufname, no buftype, no filetype) and then changes that, I'm no sure how to improve the enable function given that
![image](https://github.com/Bekaboo/dropbar.nvim/assets/70210066/173c108e-475d-4749-8944-84bc4f49d2c3)
In the blue part dropbar recognizes it as a normal buffer
```lua
enable = function(bufnr, winnr)
  print(vim.api.nvim_buf_get_name(bufnr), vim.bo[bufnr].filetype, vim.bo[bufnr].buftype, "|")
  return true -- testing
end
```

**Comment by Bekaboo** [comment]
@lopi-py How about letting `enable()` return `false` if `&ft`/`&bt`/bufname is empty?

**Comment by lopi-py** [comment]
```lua
enable = function(bufnr, winnr)
  -- default enable function
  return not vim.api.nvim_win_get_config(winnr).zindex
    and vim.bo[bufnr].buftype == ""
    and vim.bo[bufnr].filetype ~= "" -- new check
    and vim.api.nvim_buf_get_name(bufnr) ~= ""
    and not vim.wo[winnr].diff
end
```
Yeah, checking if the filetype is not empty seems to work, thanks @Bekaboo

**Comment by lopi-py** [comment]
Reopening since now a file without extension won't get the dropbar (which I like because I can click it and switch to other file, ignore the tab view, it's not neovim)
![image](https://github.com/Bekaboo/dropbar.nvim/assets/70210066/67257dbb-e702-4207-af05-0606be191fda)

**Comment by Bekaboo** [comment]
Can you try detecting the bufname in the `enable()` function instead and return `false` if it is empty or contains `xxxTrouble`, etc. ?

**Comment by lopi-py** [comment]
@Bekaboo sorry for the later response, this seems to work
```lua
enable = function(bufnr, winnr)
  local path = vim.fs.normalize(vim.api.nvim_buf_get_name(bufnr))
  if vim.bo[bufnr].buftype ~= "" or path == "" then
    return false
  end
  if path:match "Trouble$" then
    print "trouble skipped"
    return false
  end
  return not vim.wo[winnr].diff
end
```
but it is some hacky. I think [this is related](https://github.com/folke/trouble.nvim/blob/40aad004f53ae1d1ba91bcc5c29d59f07c5f01d3/lua/trouble/view.lua#L141-L142) because it sets `bufhidden` first so dropbar is reached by `OptionSet`, here is my question, why try to attach the dropbar on every `OptionSet`?, may it be worth to listen to `OptionSet` for specific options? something like this
```lua
vim.api.nvim_create_autocmd("OptionSet", {
  pattern = "buftype,filetype",
  callback = function(event)
    attach(event.buf, 0)
  end
})
```
It works fine for me even with the default `general.enable`

**Comment by Bekaboo** [comment]
> why try to attach the dropbar on every OptionSet?, may it be worth to listen to OptionSet for specific options? something like this
>
> ```
> vim.api.nvim_create_autocmd("OptionSet", {
>   pattern = "buftype,filetype,diff",
>   callback = function(event)
>     attach(event.buf, 0)
>   end
> })
> 
> ```
> It works fine for me even with the default general.enable

Because some will want to attach dropbar when some specific options is set so only listen to `&buftype`, `&filetype`, and `&diff` will be a breaking change.

**Comment by lopi-py** [comment]
What if it was configurable?
```lua
require("dropbar").setup {
  general = {
    -- string | nil
    enable_pattern = nil, -- "buftype,filetype,diff"
  },
}
```

**Comment by Bekaboo** [comment]
> What if it was configurable?

Good idea, will think about this later
