### ISSUE TITLE
[Bug]: Dropbar not working with neo-tree

### ISSUE THREAD

**Issue by franroa** [Bekaboo/dropbar.nvim#72]
### Description

When I open the file explorer in neo-tree, I am getting these errors:

`Error detected while processing WinResized Autocommands for "*":`

`Error executing lua callback: ...isco/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar.lua:101: Invalid window id: 1026
stack traceback:
	[C]: in function 'nvim_win_get_buf'
	...isco/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar.lua:101: in function <...isco/.local/share/nvim/lazy/dropbar.nvim/lua/dropbar.lua:91>`

### nvim version

0.10-dev (nightly)

### dropbar.nvim version

latest

### Operating system and version

Manjaro(arch) 6.1.44-1

### Minimal config

```Lua
LazyVim with dropbar default config
```

### Steps to reproduce

1. Open a file
2. With the file open, open the neo-tree explorer

### Expected behavior

No errors are thrown

### Actual behavior

An error is thrown, although dropbar still works properly

**Comment by Bekaboo** [comment]
@franroa Please provide a minimal config based on ghe tenplate provided. I don't debug people's whole configs.

**Comment by Bekaboo** [comment]
@franroa No... LazyVim is a pretty massive config, keep the config file as simple as possible. Only install plugins that is necessary to reproduce the error. Do not use a plugin manager.

**Comment by franroa** [comment]
I have just figured out which causes the problem. There is an incompatibility between dropbar and edgy. I have no idea how to write a minimal config though. I will create an issue on LazyVim and link this one, I think from LazyVim side is much easier to solve this, I guess, since in order to have the edgy default config I also need other plugins to be running

**Comment by franroa** [comment]
This is the issue on edgy: https://github.com/folke/edgy.nvim/issues/44

**Comment by Bekaboo** [comment]
@franroa Glad to hear that you've located the problem! It is possible that some hacks in edgy causes the issue.
