### ISSUE TITLE
Question: Different sources for different windows

### ISSUE THREAD

**Issue by MariaSolOs** [Bekaboo/dropbar.nvim#76]
Hello! I'm trying to configure `dropbar` in a way that only the window where my cursor is has all the default sources, and the other ones just use the path source.

I promise that I've studied the docs and code to try to achieve this, but for some reason the `buf` and `win` arguments in `opts.bar.sources` always match `vim.api.nvim_get_current_win()` and `vim.api.nvim_get_current_buf()`.

@Bekaboo given the quality of this plugin, I'm sure you know much more about windows/buffers/cursor positions and I would appreciate your insights here <3

**Comment by MariaSolOs** [comment]
Okay I think I made it work but I would still appreciate your input @Bekaboo in case you think there's a better way of achieving this.

```lua
require('dropbar').setup {
  general = {
    update_events = {
      win = {
        'CursorMoved',
        'CursorMovedI',
        'WinEnter',
        'WinResized',
         -- Add 'WinLeave' so that inactive windows just show the path.
        'WinLeave',
      },
    },
  },
  bar = {
    sources = function()
      local sources = require 'dropbar.sources'
      local utils = require 'dropbar.utils.source'

      -- Just show the path info for non-active windows.
      return {
        sources.path,
        {
          get_symbols = function(buf, win, cursor)
            if vim.api.nvim_get_current_win() ~= win then return {} end

            if vim.bo[buf].ft == 'markdown' then
              return sources.markdown.get_symbols(buf, win, cursor)
            end

            return utils.fallback({ sources.lsp, sources.treesitter }).get_symbols(buf, win, cursor)
          end,
        },
      }
    end
  }
}
```

**Comment by MariaSolOs** [comment]
Hmm that didn't work entirely :( The above code broke `require('dropbar.api').pick` because of the `WinLeave` event, but if I remove it then the dropbar isn't updated correctly when the cursor moves to another window.

**Comment by Bekaboo** [comment]
@MariaSolOs I think the simplest solution it that you call the update method manually on WinLeave and avoid updating the current window, it is not that hard.

> Hmm that didn't work entirely :( The above code broke require('dropbar.api').pick because of the WinLeave event

Yes that is desired because after updating a dropbar we cannot ensure the new symbols in the dropbar match the enties in the menu, so all opening menus attached to that dropbar will be closed.

**Comment by MariaSolOs** [comment]
@Bekaboo hmmm could I get another hint? I tried this but it isn't working. I think it's because (as taken from the docs) "`WinLeave` is triggered before leaving a window", and so `current_win` is in fact the actual window I want to modify :/
If I change the event below to `WinEnter`, then I break the `pick` command again...

```lua
vim.api.nvim_create_autocmd('WinLeave', {
  callback = function()
  local current_win = vim.api.nvim_get_current_win()
    for _, win in ipairs(vim.api.nvim_list_wins()) do
      if win ~= current_win then
        require('dropbar.utils.bar').exec('update', { win = win })
      end
    end
  end,
})
```

**Comment by Bekaboo** [comment]
@MariaSolOs Sorry I haven't tested it myself before commenting -- a little bit busy these days 😶 I'll give you a proper response in a week (hopefully), either by a working config snippet or some options/features builtin in the plugin.

**Comment by MariaSolOs** [comment]
No worries at all! Thank you for helping me with this <3

**Comment by MariaSolOs** [comment]
@Bekaboo After playing around with this a bit more, this is working:

```lua
-- In my setup
general = {
  update_events = {
    -- Remove the 'WinEnter' event since I handle it manually for just
    -- showing the full dropbar in the current window.
    win = { 'CursorMoved', 'CursorMovedI', 'WinResized' },
  },
}

vim.api.nvim_create_autocmd('WinEnter', {
  callback = function()
    -- Refresh the dropbars except when entering the dropbar itself.
    if vim.fn.getwininfo(vim.api.nvim_get_current_win())[1].winbar == 1 then
      require('dropbar.utils.bar').exec 'update'
    end
  end,
})
```

It seems to be working nicely (and the `pick()` command still works!) but I would still appreciate to hear your thoughts on whether you think there's a better way to do it :)

**Comment by MariaSolOs** [comment]
@Bekaboo have you had the time to think about this?

**Comment by serhez** [comment]
Hello, I'm trying to show the filepath in the winbar for inactive windows, and LSP/treesitter for active ones. Here is my attempt:
```lua
require("dropbar").setup({
  general = {
    update_events = {
      -- Remove the 'WinEnter' event since I handle it manually for just
      -- showing the full dropbar in the current window.
      win = { "CursorMoved", "CursorMovedI", "WinResized" },
    },
  },
  bar = {
    sources = function(buf, win)
      local sources = require("dropbar.sources")
      local utils = require("dropbar.utils")
      
      if vim.bo[buf].ft == "markdown" then
        return {
          sources.path,
          sources.markdown,
        }
      end
      
      if vim.bo[buf].buftype == "terminal" then
        return {
          sources.terminal,
        }
      end
      
      if vim.api.nvim_get_current_win() ~= win then
        return {
          sources.path,
        }
      end
      
      return {
        utils.source.fallback({
          sources.lsp,
          sources.treesitter,
        }),
      }
      end,
    },
  })
})
  
-- Required updates to detect active vs. inactive windows
vim.api.nvim_create_autocmd("WinEnter", {
  callback = function()
    -- Refresh the dropbars except when entering the dropbar itself.
    if vim.fn.getwininfo(vim.api.nvim_get_current_win())[1].winbar == 1 then
      require("dropbar.utils.bar").exec("update")
    end
  end,
})
```

The issue is that the active vs. inactive window detection logic is not working, I suppose it's a similar issue to the one presented here @MariaSolOs ? Is there any way to achieve this? Thank you!

**Comment by jeffglover** [comment]
I realize this is ancient, but when I search for this feature, this is pretty much the only useful discussion out there. So here's a working solution in case it helps anyone.

The problem is the `win` that is passed into sources is only the initial startup `win`. Instead, I created a custom source, `winfocus_fallback_source`, that wraps the fallback source. The inner `get_symbols` function gets called with the inactive `win` that we care about. Here's my entire lazyvim config fn.

```lua
config = function()
  local sources = require 'dropbar.sources'
  local utils = require 'dropbar.utils'

  local winfocus_fallback_source = {
    get_symbols = function(buf, win, cursor)
      if vim.api.nvim_get_current_win() == win then
        return utils.source.fallback({ sources.lsp, sources.treesitter }).get_symbols(buf, win, cursor)
      end
      return {}
    end,
  }

  require('dropbar').setup {
    bar = {
      update_debounce = 0,
      update_events = {
        win = {
          'CursorMoved',
          -- 'WinEnter',
          'WinResized',
        },
      },

      sources = function(buf)
        if vim.bo[buf].ft == 'markdown' then
          return {
            sources.path,
            sources.markdown,
          }
        end

        if vim.bo[buf].buftype == 'terminal' then
          return {
            sources.terminal,
          }
        end

        return {
          sources.path,
          winfocus_fallback_source,
        }
      end,
    },
  }

  vim.api.nvim_create_autocmd({ 'WinEnter' }, {
    group = vim.api.nvim_create_augroup('DropbarWinFocus', { clear = true }),
    callback = function()
      if vim.fn.getwininfo(vim.api.nvim_get_current_win())[1].winbar == 1 then
        utils.bar.exec 'update'
      end
    end,
  })
end,
```
