### ISSUE TITLE
[Feature]: Show only filename in path source

### ISSUE THREAD

**Issue by carlobonandriniunimi** [Bekaboo/dropbar.nvim#88]
### Problem

The only way to change the path source is to change the relative_to function in the sources.path option, with something like this:
```
relative_to = function(_)
    local fullpath = vim.api.nvim_buf_get_name(0)
    local filename = vim.fn.fnamemodify(fullpath, ":t")
    return fullpath:sub(0, #fullpath - #filename)
end,
```
That gets you something like this:
<img width="442" alt="Screenshot 2023-09-20 at 12 37 56" src="https://github.com/Bekaboo/dropbar.nvim/assets/98645146/3e1d0299-6584-4a50-9e8b-256af284d587">

The problem with this is that if you are focused on another type of window, like NvimTree, it outputs the full path from the home directory:
<img width="1202" alt="Screenshot 2023-09-20 at 12 38 16" src="https://github.com/Bekaboo/dropbar.nvim/assets/98645146/3b1e5e2b-471b-4fb6-bfc2-ece89c4e0afe">

### Expected behavior

I don't know if there is a better way to set the relative path, but it would be cool if there would be an option to only output the filename without the full path from the current directory (I think it's cleaner and not so cluttered).

**Comment by willothy** [comment]
Not sure about only displaying the filename, but you could try having `relative_to` use the tabpage or global cwd with `getcwd(-1)` or `getcwd(-1, -1)`.

**Comment by carlobonandriniunimi** [comment]
> Not sure about only displaying the filename, but you could try having `relative_to` use the tabpage or global cwd with `getcwd(-1)` or `getcwd(-1, -1)`.

Didn't really do much for me, my solution seems to be better for now, but It would be cool to have the option to remove the file path

**Comment by Bekaboo** [comment]
@carlobonandriniunimi You can create a new source as a wrapper of the builtin path source which only returns the last element (the filename).

**Comment by Bekaboo** [comment]
@carlobonandriniunimi There is a [section in README](https://github.com/Bekaboo/dropbar.nvim#making-a-new-source) about how to do this. You just create a table with a function `get_symbols` which is a wrapper of the `get_symbols` functions of the `path` source that only returns the last element from the original `get_symbols` function.

**Comment by carlobonandriniunimi** [comment]
> @carlobonandriniunimi There is a [section in README](https://github.com/Bekaboo/dropbar.nvim#making-a-new-source) about how to do this. You just create a table with a function `get_symbols` which is a wrapper of the `get_symbols` functions of the `path` source that only returns the last element from the original `get_symbols` function.

This works thanks!
Is this what you were thinking?
```
      local filename = {
        get_symbols = function(buff, win, cursor)
          local symbols = sources.path.get_symbols(buff, win, cursor)
          return { symbols[#symbols] }
        end,
      }
```

**Comment by Bekaboo** [comment]
@carlobonandriniunimi Yes, `filename` will be a new source that returns a symbols list that contains only the last element.

**Comment by carlobonandriniunimi** [comment]
Thanks for the help, closing the issue
