### ISSUE TITLE
[Bug]: `<C-w>` cause error in fuzzy search mode

### ISSUE THREAD

**Issue by Bekaboo** [Bekaboo/dropbar.nvim#97]
### Description

In fuzzy search mode, deleting texts before cursor using `<C-w>` or `<C-u>` etc. will make `fzf_entry.pos` to `nil`, triggering an error in https://github.com/Bekaboo/dropbar.nvim/blob/1a6c8794d5da9e026561354e7e970b2abf862a59/lua/dropbar/menu.lua#L1042

### nvim version

v0.10.0-dev-1224+gdfa8b582a6

### dropbar.nvim version

1a6c8794d5da9e026561354e7e970b2abf862a59

### Operating system and version

Linux 6.1.54.15.realtime1-2-rt-lts

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

cloned_path = cloned_root .. '/telescope-fzf-native'
url = 'https://github.com/nvim-telescope/telescope-fzf-native.nvim'

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
  vim.fn.system({ 'make', '-C', cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

1. Save the configuration above as `minimal.lua`
2. Make sure `telescope-fzf-native` is in `&rtp`
3. `nvim -u minimal.lua`
4. Open an arbitrary file
5. Open dropbar menu
6. Press `i` to enter fuzzy search mode
7. Search for some pattern
8. Press `<C-w>` to delete word before cursor
9. See the error

### Expected behavior

Should not error

### Actual behavior

Error.

### Additional information

https://github.com/Bekaboo/dropbar.nvim/assets/76579810/ecb23b6d-bfe3-465e-9164-40507a2033de

**Comment by Bekaboo** [comment]
@willothy I believe you can come up with a better fix to this bug than I can.

**Comment by willothy** [comment]
For sure, I'll look into this tomorrow.

**Comment by willothy** [comment]
Nevermind, found it pretty quickly. Can you see if that works?
